### ISSUE TITLE
getParameterSamples cannot be called with PestoOptions instance

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#59] opened 2017-03-08 12:45 UTC
Due to getParameterSamples.m 118-120
```
   opt.number = parameters.number;
   opt.min    = parameters.min;
   opt.max    = parameters.max;
```
getParameterSamples cannot be called with PestoOptions instance, because these members do not exist.
(see `runPestoTests`)

(why) is it required to copy these values into `opt`?

**Comment by BBallnus** [comment] 2017-03-08 12:54
This is currently required, because sampling methods need boundaries and do not get the parameter struct as input so far. This basically makes the sampling methods currently function as standalone without the need for other PESTO functions or structures.

This discussion is very similar to the discussion about opt.objOutNumber -> parameters.objOutNumber from a couple of days ago, where we decided to not rearrange the option, since Paul did not want to toss the entire parameter struct into some sub-function. I personally do not want to make the sampling routines more dependent than necessary.

**Comment by dweindl** [comment] 2017-03-08 13:01
Yes, it refers to the previous discussion. However, we should have a unified interface now.

What is wrong with changing
> function res = performPT( logPostHandle, opt )

to
> function res = performPT( logPostHandle, par, opt )

?

**Comment by BBallnus** [comment] 2017-03-08 13:12
I think the interface is unified, since the user only interacts with
> function parameters = getParameterSamples(parameters, objFkt, opt)
and not with performPT, which is private.

Your suggested change is possible indeed. Yet I'm not convinced it is necessary. :)

**Comment by dweindl** [comment] 2017-03-08 13:15
> I think the interface is unified, since the user only interacts with
    function parameters = getParameterSamples(parameters, objFkt, opt)

Not exactly, since `opt` is of a different type than for all other functions.

**Comment by BBallnus** [comment] 2017-03-08 13:21
Gonna upload an adapted version, please let me know if this works for you

**Comment by dweindl** [comment] 2017-03-08 13:37
Something is wrong with `checkSamplingOptions`

```
    Error using checkSamplingOptions (line 21)
    Please specify the type of objective function, e.g. opt.obj_type = "log-posterior"
    
    Error in getParameterSamples (line 118)
       checkSamplingOptions(parameters,opt);

    
    Error in ConversionReactionTest/testSamplingSingleChainAM (line 109)
                parameters = getParameterSamples(testCase.parameters, testCase.objectiveFunction, optionsMultistart);
```
... although 
```
K>> opt.obj_type

ans =

log-posterior
```

To reproduce, run `runPestoTests`

**Comment by BBallnus** [comment] 2017-03-08 13:47
This is not reproducible for me - neither by calling the example directly nor calling it via runPestoTests

**Comment by dweindl** [comment] 2017-03-08 13:56
@FFroehlich Does `runPestoTests` complete successfully for you?

**Comment by FFroehlich** [comment] 2017-03-08 13:57
runPestoTests runs fine for me.

**Comment by dweindl** [comment] 2017-03-08 13:59
(On develop?)

For me in MATLAB Version: 9.0.0.341360 (R2016a) on Linux it does not.

**Comment by FFroehlich** [comment] 2017-03-08 14:05
I get the same:

Error occurred in ConversionReactionTest/testSamplingSingleChainAM and it did not run to completion.

    ---------
    Error ID:
    ---------
    ''

    --------------
    Error Details:
    --------------
    Error using checkSamplingOptions (line 21)
    Please specify the type of objective function, e.g. opt.obj_type = "log-posterior"
    Error in getParameterSamples (line 118)
       checkSamplingOptions(parameters,opt);

    Error in ConversionReactionTest/testSamplingSingleChainAM (line 109)
                parameters = getParameterSamples(testCase.parameters, testCase.objectiveFunction, optionsMultistart);

**Comment by BBallnus** [comment] 2017-03-08 14:32
Now I get it! Sorry for the confusion, I was still talking about RunTestExamples, while you guys were talking about runPestoTests. I actually CAN reproduce the error - I'll have a look. Never touched runPestoTests so far.

**Comment by paulstapor** [comment] 2017-03-08 23:48
I'm currently implementing a class PestoSamplingOptions. This will make this at least mostly uniform...

**Comment by BBallnus** [comment] 2017-03-09 10:28
This issue should be fixed, since Paul and I shifted some code to a sampling options class.

**Comment by BBallnus** [comment] 2017-03-09 10:30
After Reading Fabian comment in #43, I decided to reopen it until we have updated the Master-Branch.

**Closed** 2017-03-14 11:58 UTC
