### ISSUE TITLE
Warnings when running mainExampleGauss.m

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#58] opened 2017-03-08 12:05 UTC
Expected behavior:
The provided examples should not issue any warnings or errors.

Actual behavior:
Got the warnings shown below when running mainExampleGauss.m. 

```
Progress: 100 %

ans = 

  Figure (8: plotParameterUncertainty) with properties:

      Number: 8
        Name: 'plotParameterUncertainty'
       Color: [0.9400 0.9400 0.9400]
    Position: [1000 918 560 420]
       Units: 'pixels'

  Show all properties

Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 
Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 
Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 
Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 
Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 
Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 
Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 
Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 
Warning: No valid values for sigma found! Not plotting approximation. 
> In plotParameterUncertainty (line 613)
  In plotParameterSamples (line 43) 

ans = 

  Figure (1: plotParameterUncertainty) with properties:

      Number: 1
        Name: 'plotParameterUncertainty'
       Color: [0.9400 0.9400 0.9400]
    Position: [1000 918 560 420]
       Units: 'pixels'

  Show all properties
```

**Comment by BBallnus** [comment] 2017-03-08 12:40
This is caused by the fact, that there is no optimization and thus no local hessian in this example. This not not a real issue since sampling methods are supposed to work standalone. However, raising those warnings in the example is not convenient from my perspective. 

Possible fixes: performing MS or removing the way how those warnings are handled. I prefer the latter. Any suggestions?

**Comment by dweindl** [comment] 2017-03-08 12:46
If it is supposed to work without prior optimization, then I agree that no warnings should be issued.

**Comment by BBallnus** [comment] 2017-03-08 12:56
Ok, I'll have a look at the warning code.

**Comment by BBallnus** [comment] 2017-03-08 13:25
should be fixed now

**Comment by BBallnus** [comment] 2017-03-09 10:31
After Reading Fabian comment in #43, I decided to reopen it until we have updated the Master-Branch.

**Closed** 2017-03-14 11:59 UTC
