### ISSUE TITLE
Error in mainTransfection.m:257 (sampling)

### ISSUE THREAD

**Issue by dweindl** [ICB-DCM/PESTO#60] opened 2017-03-08 13:27 UTC
```
% Initialize the chains by choosing a random inital point and a 'large'
% covariance matrix
samplingOpt.theta0                = (parameters.min' + ...
   (parameters.max' - parameters.min') .* rand(5,5))';
```
> Error using  .* 
Matrix dimensions must agree.

**Comment by BBallnus** [comment] 2017-03-08 13:41
I cannot reproduce that error

**Comment by dweindl** [comment] 2017-03-08 13:52
For me, the problem persists. 
 @FFroehlich  @paulstapor Can you reproduce this by running mainTransfection.m in a clean workspace?

**Comment by FFroehlich** [comment] 2017-03-08 13:59
I cannot find the lines mentioned above in mainTransfection.m the master branch.

**Comment by dweindl** [comment] 2017-03-08 14:00
Was talking about `develop`, sorry, my mistake.

**Comment by FFroehlich** [comment] 2017-03-08 14:04
also runs fine for me, although the progress text updated in getParameterSamples is quite nasty.

**Comment by dweindl** [comment] 2017-03-08 14:11
This code 
```
parameters.min    = [-2; -5; -5; -5; -2];
parameters.max    = [1; 5; 5; 5; 2];
theta0            = (parameters.max' - parameters.min') .* rand(5,5);
```
fails on 
>MATLAB Version: 9.0.0.341360 (R2016a)
Operating System: Linux 4.4.0-64-generic #85-Ubuntu SMP Mon Feb 20 11:50:30 UTC 2017 x86_64
Java Version: Java 1.7.0_60-b19 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

**Comment by FFroehlich** [comment] 2017-03-08 14:14
fine on 

> MATLAB Version: 9.1.0.441655 (R2016b)
> MATLAB License Number: 834159
> Operating System: Mac OS X  Version: 10.12.1 Build: 16B2555 
> Java Version: Java 1.7.0_75-b13 with Oracle Corporation Java HotSpot(TM) 64-Bit Server VM mixed mode

I think this is because in 9.1 they made pointwise multiplication (A.*B) fall back to bsxfun(@times,A,B) for (<2D?) matrices/vectors. So bsxfun(@times,(parameters.max' - parameters.min'),rand(5,5)) should do the job.

**Comment by dweindl** [comment] 2017-03-08 14:30
Ah. Thanks for the info. 
But why do we even use 
> rand(5,5) 

and not
> rand(1,5)
?

**Comment by BBallnus** [comment] 2017-03-08 14:36
5 temperatures, 5 parameters - shall we close this issue?

**Comment by dweindl** [comment] 2017-03-08 14:38
No.
>samplingOpt.theta0                = (parameters.min' + ...
   bsxfun(@times, parameters.max' - parameters.min', rand(5,5)))';

> Error using  + 
Matrix dimensions must agree.

**Comment by dweindl** [comment] 2017-03-08 14:40
> samplingOpt.theta0                = bsxfun(@plus, parameters.min', ...
   bsxfun(@times, parameters.max' - parameters.min', rand(5,5)))';

That should do the right thing, right?

**Comment by paulstapor** [comment] 2017-03-08 23:56
Currently trying to reunify things, I'm getting the error 

Error using bar (line 142)
X must be same length as Y.

Error in plotParameterUncertainty (line 223)
                    h = bar(X,N/max(N),1,'facecolor',options.S.col(k,:),'edgecolor',[0.4,0.4,0.4]); hold
                    on;

Error in plotParameterSamples (line 43)
        fh = plotParameterUncertainty(parameters, varargin{1}, varargin{2}, varargin{3}, varargin{4});

Error in mainTransfection (line 302)
plotParameterSamples(parameters,'1D',[],[],samplingPlottingOpt)

Since I did some changes, this may very well be due to my changes. Anyway:
@BBallnus : Could you implement a standard plotting at the end of getParameterSamples (and getPropertySamples) if strcmp(options.mode, 'visual')? This would have some advantages (consistency, easy-to-use), among others: I wouldn't have to fix the error I just mentioned. ;-)

**Comment by BBallnus** [comment] 2017-03-09 07:49
@paulstapor I will!

**Comment by BBallnus** [comment] 2017-03-09 10:27
I have added the output functionality to getParameterSamples.

Also I think the original problem was solved, thus I'm closing this issue.

**Comment by BBallnus** [comment] 2017-03-09 10:31
After Reading Fabian comment in #43, I decided to reopen it until we have updated the Master-Branch.

**Comment by dweindl** [comment] 2017-03-09 11:15
@paulstapor Please don't reopen a fixed issue for an unrelated new issue, but file a new one.

**Closed** 2017-03-14 11:55 UTC
Labels: bug
