### ISSUE TITLE
"inconsistent" settings for indices in profile calculation

### ISSUE THREAD

**Issue by FFroehlich** [ICB-DCM/PESTO#81] opened 2017-03-21 10:39 UTC
previously I could simply specify `options.parameter_index = ip` to compute the profiles only for parameter with index `ip` and I think this should still be the case.
Please fix default values for options.profile_optim_index and options.profile_integ_index and implement set routines for options.parameter_index and options.profile_optim_index and options.profile_integ_index that adapt these values in a smart way (or another smart way that minimizes user interaction).

**Comment by paulstapor** [comment] 2017-03-21 13:37
That's definitely a bug of which I will take care of...
The idea was: no index specified: all profiles optimized.
parameter_index set: use that one
profile_optim_index/profile_integ_index set: use that one instead of parameter_index, since it's more specific

**Comment by paulstapor** [comment] 2017-03-21 21:40
I just checked it. I could not reproduce the error I thought you found...

Currently, getPArameterProfiles throws the error you mentioned in the following case: If options.parameter_index AND options.profile_optim[integ]_index are defined in a way which do not fit together.

It is still possible to only set options.parameter_index = [subset] and do profiling on that. At least from what I've tested...

Can you give some more info, when exactly the error occurred?

**Comment by paulstapor** [comment] 2017-03-21 22:20
I wanted to do something super-smart with some possibilities for short cut definitions and created a logical monster. Never gonna do this again. Now: Either options are consistently and logically defined, or slap the user: no intelligent short-cuts which mess up everything.

Now one can specify EITHER parameter_index OR profile_optim_index OR profile_integ_index (or whatever kind of consistent combinations, together with profile_method)...

I hope it works now (tested quite some cases), fixed on develop....

**Comment by dweindl** [comment] 2017-03-24 11:03
This can be closed, right?

**Comment by paulstapor** [comment] 2017-03-24 11:39
right

**Closed by paulstapor** 2017-03-24 11:39 UTC
Labels: bug
